### ISSUE TITLE
auro-icon: @latest call does not resolve to latest /icons repository

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-icon#11]
## Describe the bug
After implementing the new elite and boarding icons, 404s were returned for this component.
https://github.com/AlaskaAirlines/auro-icon/blob/master/src/auro-icon.js#L114
seems to be the issue.
## To Reproduce
Implement in-flight/boarding as an <auro-icon>

## Expected behavior
The icon renders 

## Screenshots
![image](https://user-images.githubusercontent.com/7005799/97058799-a5961280-1543-11eb-8a70-0563d64cacfd.png)

## Desktop (please complete the following information):
 - OS: os x
 - Browser chrome
 - Version latest

## Additional context
https://github.com/AlaskaAirlines/auro-icon/blob/master/src/auro-icon.js#L114 @latest appears to be broken here

**Comment by blackfalcon** [comment]
@gusnaughton using the following code in the demo site

```html
<div>
  <auro-icon category="in-flight" name="boarding"></auro-icon>
</div>
<div>
   <auro-icon category="in-flight" name="elite"></auro-icon>
</div>
```

I get ... 

<img width="392" alt="Screen Shot 2020-10-23 at 4 10 53 PM" src="https://user-images.githubusercontent.com/181089/97061069-56071500-154a-11eb-8027-040766964f94.png">

The SVGs are available. 

![](https://unpkg.com/@alaskaairux/icons@4.0.2/dist/icons/in-flight/boarding.svg)
![](https://unpkg.com/@alaskaairux/icons@4.0.2/dist/icons/in-flight/elite.svg)
