### ISSUE TITLE
auro-icon: fixed Alaska logos

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-icon#12]
## Is your feature request related to a problem? Please describe.

Update the use of the Alaska logo to correspond to the official logo use specification. 

![cfd37622-2c9e-4cf5-b513-badc294c36a5](https://user-images.githubusercontent.com/181089/98297042-af1e7200-1f68-11eb-8db5-3dd6877a8eb5.jpg)

### Asset

See the following zip archive of design assets to be used. 
[Alaska logo.zip](https://github.com/AlaskaAirlines/auro-icon/files/5478608/Alaska.logo.zip)

**Comment by sryckman** [comment]
[Alaska logo.zip](https://github.com/AlaskaAirlines/auro-icon/files/5520272/Alaska.logo.zip)

**Comment by blackfalcon** [comment]
The decision was made to create a new auro-alaska custom element to address the concerns of this update.
