### ISSUE TITLE
[issue summary] Missing semicolon in iconStyle.scss

### ISSUE THREAD

**Issue by joelflachsbart** [AlaskaAirlines/auro-icon#128]
### Please verify the version of auro-icon you have installed

4.4

### Please describe the bug

Line 86 of iconStyle.css is missing a semicolon which can cause unexpected behavior when the browser tries to interpret the style rules.

![image](https://github.com/user-attachments/assets/eda55478-9211-4a16-a528-8fdde8b1553c)

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### What browsers are you seeing the problem on?

Chrome

**Comment by joelflachsbart** [comment]
@jason-capsule42 FYI this is still a bug, the typo got copied over to a new file

**Comment by braven112** [comment]
Reopening so we can validate this is still an issue on Monday
