### ISSUE TITLE
Unpak CDN is causing delays

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-icon#13]
# General Support Request

![MicrosoftTeams-image](https://user-images.githubusercontent.com/181089/99568233-08809b00-2984-11eb-8b53-3aca2917cfc1.png)

It is being noticed that using unpak.com for a CDN resource is causing blocking issues with the pages in the prod site. 

## Possible Solution

There are a couple of things on the table here. The first one we want to look at is moving the Auro Icons npm package to an alternate CDN location to see if this improves performance. @geoffrich had some recommendations for alternate CDNs when researching the new component bundled work. @gusnaughton has a 'working' CDN solution for Hanger, but it was agreed that this is not ideal. @tsalright represents the Platform team where it was disguised as more appropriate for CDN management. 

What say we all? 

An alternate solution is to make icons a dependency of the app and the icons will be shipped with the prod code thus reducing that secondary call.

**Comment by gusnaughton** [comment]
>  @gusnaughton has a 'working' CDN solution for Hanger, but it was agreed that this is not ideal.
To be clear, this is not ideal due to the consumption model surrounding a non-centralized CDN, however our Azure Frontdoor/Storage Account solution has proven to work perfectly over the last 9 months at "flight scale" (matrix page shopping during stress times)

> An alternate solution is to make icons a dependency of the app and the icons will be shipped with the prod code thus reducing that secondary call.

This feels heavy. I'm not super comfortable with shipping our entire iconography library to guests when there may be only one icon added to a page.

**Comment by tsalright** [comment]
I can jump on getting a centralized Alaska Airlines hosted CDN in Azure. This would be similar to the p2p one, but it would be for all AlaskaAirlines.

**Comment by tsalright** [comment]
@gusnaughton We should connect on what p2p did for their setup. I can get a centralized one up and running and we can get stuff moving. We need to do this ASAP before Cyber Monday.

**Comment by geoffrich** [comment]
It seems like there's two issues:

1. We call unpkg with the version set to latest, which means the first icon request results in a redirect to whatever the latest version is. This means every icon request is doubled. We can mitigate this by pinning the version with unpkg, or by standing up our own CDN.
2. Duplicate fetch requests when the icon is on the page multiple times. We'd still have this issue with our own CDN. Might have to implement @gusnaughton's fetch wrapper with a cache

```js
import 'whatwg-fetch';

const _fetchMap = new Map();

/**
 * Minimal cache layer for Fetch API requests to prevent duplicate requests and load to target servers.
 *
 * @param {String} requestUri absolute or relative URI for the Fetch API request
 * @param {Object} options an optional key-value set of options, currently only a custom response parser
 * @return {Promise<String>} Fetch API response text
 */
export default function cacheFetch(requestUri, options = {responseParser: ((res) => res.text())}) {
  const responseParser = options.responseParser || ((res) => res.text());
  if (!_fetchMap.has(requestUri)) {
    _fetchMap.set(requestUri, fetch(requestUri).then(responseParser));
  }
  return _fetchMap.get(requestUri);
}
```

**Comment by littleninja** [comment]
@tsalright I'm curious about the centralized CDN solution (for AlaskaAirlines.com, correct?). Mainly permissions and access management: for innersource code pushed to the CDN, will access be scoped per project? How do we prevent namespace collisions (seen this in practice)? I'm happy to lend a hand moving this forward!

**Comment by littleninja** [comment]
@geoffrich

> Duplicate fetch requests when the icon is on the page multiple times. We'd still have this issue with our own CDN. Might have to implement @gusnaughton's fetch wrapper with a cache

Depending on how we implement a CDN, would it be possible to still form a request for latest (example: cdn.alaskaair.com/icons/logo-ba.svg) and deploy latest with an Etag strategy for caching? The fetch wrapper cache does come with a trade-off, each request is duplicated in-memory (inside _fetchMap).

Could one or multiple SVG sprites help here?

**Comment by geoffrich** [comment]
> 
> 
> @geoffrich
> 
> > Duplicate fetch requests when the icon is on the page multiple times. We'd still have this issue with our own CDN. Might have to implement @gusnaughton's fetch wrapper with a cache
> 
> Depending on how we implement a CDN, would it be possible to still form a request for latest (example: cdn.alaskaair.com/icons/logo-ba.svg) and deploy latest with an Etag strategy for caching? The fetch wrapper cache does come with a trade-off, each request is duplicated in-memory (inside _fetchMap).
> 
> Could one or multiple SVG sprites help here?

Didn't realize there was a memory tradeoff, thanks for pointing that out! I'm afraid I don't know enough about caching strategy to speak to an Etag strategy.

**Comment by blackfalcon** [comment]
Note: @littleninja PR to address multiple fetch requests has been merged to assist with element performance.

**Comment by blackfalcon** [comment]
@tsalright what is the status of this?

**Comment by tsalright** [comment]
Still waiting on Gus and Geoff to validate and tell me to move forward.

**Comment by blackfalcon** [comment]
Reducing assignees to only @tsalright. He is in the process of handing off this work to the Content team to carry this across the finish line. 

Please @ me in the comments when appropriate.

**Comment by blackfalcon** [comment]
This project is under review from another team. 

Auro is also looking at using Skypack as a resource.

**Comment by blackfalcon** [comment]
I am closing this issue as the work has been moved into multiple directions. As far as Auro is concerned, there is no work to be done here. Issues #24 and #23 are intended to solve related issues to this problem. 

As for the CDN development, that has been 100% moved to the Content team and Auro is only a stakeholder.
