### ISSUE TITLE
auro-icon: Bundled output includes every icon in auro-icons

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-icon#2]
## Describe the bug
When bundling the component, every icon in auro-icons is included in [polyfills.js](https://unpkg.com/@alaskaairux/auro-icon@1.0.1/dist/polyfills.js). This results in a bundle that's over 600 KB.

I assume this would happen in any consumer of the component who bundles it themselves.

## To Reproduce
1. `npm run bundler`
2. Observe that the size of polyfills.js is 635KB

## Expected behavior
Only icons that are used are bundled with auro-icon.

## Additional context
This is a show-stopper for me using the auro-icon component. Importing the icons directly myself results in a massively smaller bundle.

This might need some rethinking of how the icons are dynamically imported. Maybe the component API could be reworked to take in the SVG string or object and wrap around that? At least that way the consumer wouldn't have to parse the SVG string into the DOM themselves.

**Comment by blackfalcon** [comment]
Is this only an issue with the pre-bundled version? Does using this in a dynamic environment still have the same bloat?

**Comment by tsalright** [comment]
I am also running into an issue trying to use this in other auro demos. I am going to update this to use the CDN instead of the icons package directly. That should fix this issue and others we are seeing trying to use it.
