### ISSUE TITLE
auro-icon: labels in a list

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-icon#26]
## Is your feature request related to a problem? Please describe.
Stacking the icons with labels vertically doesn't provide enough space between each icon.

## Describe the solution you'd like
Ideally a simple way to showcase multiple icons in a vertical list or as an unordered list.

## Describe alternatives you've considered
A way to decide where to put the label below the icon.
![image](https://user-images.githubusercontent.com/5118118/118895905-eed0f980-b8bb-11eb-96e3-386132b77c68.png)
![image](https://user-images.githubusercontent.com/5118118/118895974-0b6d3180-b8bc-11eb-9f6a-b7f5dbb7b6a2.png)

**Comment by blackfalcon** [comment]
Schedule a meeting to discuss options with this request.

**Comment by blackfalcon** [comment]
There are things that can be done with the auro-icon element with other HTML and CSS that will make the shape you are looking for. I am hesitant to add a lot of styling support to this base element. The following example meets one of the needs without adding complexity to the element. 

```html
<link rel="stylesheet" href="https://unpkg.com/@alaskaairux/design-tokens@latest/dist/tokens/CSSCustomProperties.css" />
<link rel="stylesheet" href="https://unpkg.com/@alaskaairux/webcorestylesheets@latest/dist/bundled/essentials.css" />

<script src="https://unpkg.com/@alaskaairux/auro-icon@latest/dist/auro-icon__bundled.es5.js" nomodule></script>
<script src="https://unpkg.com/@alaskaairux/auro-icon@latest/dist/auro-icon__bundled.js" type="module"></script>

<style>
ul, li { margin: 0; padding: 0}
li {
  list-style: none;
  margin-bottom: 0.5rem;
}

.space { margin-left: 0.5rem;}

</style>
	
<ul>
	<li><auro-icon label category="in-flight" name="wifi"><span class="space">Wi-Fi</span></auro-icon>
	<li><auro-icon label category="in-flight" name="wifi"><span class="space">Wi-Fi</span></auro-icon>
	<li><auro-icon label category="in-flight" name="wifi"><span class="space">Wi-Fi</span></auro-icon>
	<li><auro-icon label category="in-flight" name="wifi"><span class="space">Wi-Fi</span></auro-icon>
	<li><auro-icon label category="in-flight" name="wifi"><span class="space">Wi-Fi</span></auro-icon>
```

<img width="322" alt="Screen Shot 2021-05-20 at 11 01 43 AM" src="https://user-images.githubusercontent.com/181089/119027077-c64c0c80-b95a-11eb-9f93-0870ae491f98.png">

**Comment by braven112** [comment]
Work with Amanda to come up with the specs for this component.
