### ISSUE TITLE
Allow for dynamic name change to trigger icon change

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-icon#31]
## Is your feature request related to a problem? Please describe.

See comment https://github.com/AlaskaAirlines/auro-input/pull/48#discussion_r675778770

Summary: when nesting auro-icon inside auro-input, changing the `name` value did not trigger the icon to re-fetch. 

> I think updating auro-icon is the most straightforward approach here -- when name changes, re-fetch the icon.

## Describe the solution you'd like

Update the auro-icon element to allow for outer-context dynamic updating of the `name` and `category` to trigger a re-fetch of the icon from the CDN. 

## Describe alternatives you've considered

Hacks. Nothing but hacks. 

## Additional context

https://github.com/AlaskaAirlines/auro-input/pull/48

**Comment by danhiel** [comment]
Hi, are there any updates on this feature? @blackfalcon

**Comment by blackfalcon** [comment]
Yes and no. When we ran into this issue, the solution we came up with is here https://github.com/AlaskaAirlines/auro-input/blob/main/src/auro-input.js#L98-L104

It hasn't been prioritized to come back to this issue and the solution with input has been working without any real issues. 

@danhiel is there something specific you are looking for?

**Comment by DZwell** [comment]
@blackfalcon  We'd like to be able to conditionally render icons based on some state variable, like this:
![image](https://user-images.githubusercontent.com/10947475/189929565-9d206082-cc94-4850-b361-f899a38516fb.png)


You can see from the below GIF that the name updates but nothing underneath it does. Is there a way to force a rerender of the shadow root?

![icon-no-rerender](https://user-images.githubusercontent.com/10947475/189928357-7a7e014a-7a56-41b4-8c0d-a39d37466b28.gif)

**Comment by danhiel** [comment]
@blackfalcon Also, is it possible for the auro-icon to re-render whenever the accent property changes? We would like to be able to change the color of the icon dynamically

**Comment by blackfalcon** [comment]
> @blackfalcon We'd like to be able to conditionally render icons based on some state variable, like this: ![image](https://user-images.githubusercontent.com/10947475/189929565-9d206082-cc94-4850-b361-f899a38516fb.png)
> 
> You can see from the below GIF that the name updates but nothing underneath it does. Is there a way to force a rerender of the shadow root?
> 
> ![icon-no-rerender](https://user-images.githubusercontent.com/10947475/189928357-7a7e014a-7a56-41b4-8c0d-a39d37466b28.gif) [ ![icon-no-rerender](https://user-images.githubusercontent.com/10947475/189928357-7a7e014a-7a56-41b4-8c0d-a39d37466b28.gif) ](https://user-images.githubusercontent.com/10947475/189928357-7a7e014a-7a56-41b4-8c0d-a39d37466b28.gif) [ ](https://user-images.githubusercontent.com/10947475/189928357-7a7e014a-7a56-41b4-8c0d-a39d37466b28.gif)

This is the current workaround https://github.com/AlaskaAirlines/auro-icon/issues/31#issuecomment-1212418057

**Comment by blackfalcon** [comment]
> @blackfalcon Also, is it possible for the auro-icon to re-render whenever the accent property changes? We would like to be able to change the color of the icon dynamically

I need to know more about this. From what I can see, removing `accent` or `error` from the DOM, the element changes that color.

**Comment by blackfalcon** [comment]
At the end of the day, there is no real workaround for getting auro-icon to update the CDN call by simply changing the attribute name. In this case, the recommendation is to use the AuroIcons repo itself and access the SVGs directly to enable the dynamic interface desired. 

See [AuroIcons README](https://github.com/AlaskaAirlines/Icons#react)
