### ISSUE TITLE
v4.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-icon#33]
## NEXT MAJOR release 

The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v4.0-rc` branch.
>- [x] #30 
>- [ ] #31 
>- [ ] #24 

Do this last
- [ ] #16

**Comment by blackfalcon** [comment]
@braven112 I'd like to move this up. The work here is pretty quick. There is no need for a blueprint (covered by icon design spec) and it'd be nice to have this knocked off the list of repos to upgrade.

**Comment by braven112** [comment]
Closing this RC and added the individual issues to our backlog and included all the issues in the 4.0 milestone.
