### ISSUE TITLE
icon label centered versus aligned to top

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-icon#34]
## Is your feature request related to a problem? Please describe.

Current state:
![image](https://user-images.githubusercontent.com/7005799/136879592-ca0c5d95-75e2-429f-bcc5-83a1a6c7e979.png)

Desired state:
![image](https://user-images.githubusercontent.com/7005799/136879560-c42030c6-685b-41b5-a8e3-e26a2aa122a8.png)

## Describe the solution you'd like
I'd like to remove or parameterize the align-items:center; style on .label

![image](https://user-images.githubusercontent.com/7005799/136879674-eed8746d-d9d9-41cf-bb7c-9e29e58c53e0.png)

Would updating this impact any existing placements? Open to any suggestions for API shape.

**Comment by KyleJones2** [comment]
Confirmation from UI designer - Yes, we'd like to make the icon and text top aligned, please. Thank you!
