### ISSUE TITLE
customSize not respected in Firefox after initial render

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-icon#44]
## Describe the bug
The icon gets gigantic if you try to inspect it or the page re-renders in Firefox. The default for icons is `auro-size-lg` (24px x 24px) but the icon gets exponentially larger than that, then eventually shrinks down to the default size (which is still larger than the customSize I'm trying to apply)

## To Reproduce
1. Use auro-icon with the customeSize property (`<auro-icon customSize class="icon" slot="trigger" category="alert" name="information-stroke"></auro-icon>`)
2. Apply the styles via CSS

`  .icon {
    height: 16px !important;
    min-width: 16px !important;
  }`
3. Right click and inspect the element (I'm also able to repro by clicking things on the page that force a re-render. This one is a little tricky in that I' having a hard time nailing down what specific part is causing the issue)
4. Watch the icon grow

## Expected behavior
The icon should not change size unless I tell it to.

## Screenshots
![auro-icon-custom-size](https://user-images.githubusercontent.com/10947475/165164019-4aa5312b-7327-47e6-8e95-c4fec7a39a76.gif)

## Desktop (please complete the following information):
 - Browser: Firefox
 - Version: 99.0.1

**Comment by geoffrich** [comment]
This is going to be super hard to reproduce with only a gif. Can you provide a minimal sample repo or code sample that reproduces the issue? Otherwise it's hard to know whether this is a component issue, a React issue, or something else entirely.

**Comment by DZwell** [comment]
Sure thing

**Comment by blackfalcon** [comment]
@DZwell can you repo this issue wth the Auro doc site? https://auro.alaskaair.com/components/auro/icon

Like @geoffrich said, this is really hard for us to repro on our end.

**Comment by blackfalcon** [comment]
It should also be noted that `customSize` isn't a functional property. This is only a CSS attribute. 
https://github.com/AlaskaAirlines/auro-icon/search?q=customSize

**Comment by DZwell** [comment]
I'm going to close this one for now as I'm having a hard time pinning down the exact repro steps. Also, since this only appears in Firefox and our FF user base is only around 4%, I don't feel like spending an inordinate amount of time on this. As always, thanks for the quick response!
