### ISSUE TITLE
Alaska logo icon that can change colors

### ISSUE THREAD

**Issue by diana-wang** [AlaskaAirlines/auro-icon#7]
**Is your feature request related to a problem? Please describe.**
I am hoping to add an alaska logo (like [logos/logo-AS.svg](https://github.com/AlaskaAirlines/Icons/blob/master/src/icons/logos/logo-AS.svg)) to a page with a dark background.
![image](https://user-images.githubusercontent.com/11242098/95376110-702bcc80-0895-11eb-86de-721deb10007f.png)

Unfortunately, logos/logo-AS.svg has a fill color embedded in its path, making it impossible to overwrite the color with CSS. 
![image](https://user-images.githubusercontent.com/11242098/95376273-b97c1c00-0895-11eb-909e-1941b000c602.png)

**Describe the solution you'd like**
There's a few different options that would work:
- Creating a second AS logo with the fill color desired (e.g. logos/logo-AS-ondark.svg). This would limit the number of color options (which may be desireable as it is a logo). However, it isn't as scalable if more colors need to be added. It also isn't maintainable as, if there is a design change, all logo-AS icons need to be updated.
- Creating an Alaska logo icon that inherits ```currentColor``` like the other icons. This is more scalable and maintainable, but might be too open ended color-wise for a company logo
- Creating a separate logo component that limits the color options. This would be the most work and would need to be scoped and defined properly as it may cause confusion, especially if the other company logos still live in this repository.

**Describe alternatives you've considered**
Please see above for a few options

**Additional context**
Please see above for screenshots

**Comment by diana-wang** [comment]
Gotcha, that makes sense. Thank you for the example!

**Comment by blackfalcon** [comment]
@diana-wang I think we have a plan here, how do you want to move forward? I would like to close this and open a new issue with a direct specification. Are you available to support the work?

**Comment by diana-wang** [comment]
Yup! I’ll be happy to work on this.
